### ISSUE TITLE
Rename license to licenseKey

### ISSUE THREAD

**Issue by robrap** [victorrodrigues/html-webpack-new-relic-plugin#7]
@victorrodrigues: I'm wondering if you would be willing to land a breaking change, renaming `license` to `licenseKey` to clean up the code and to have more consistency, matching all the names in the New Relic snippet.

See https://github.com/edx/html-webpack-new-relic-plugin/pull/3#discussion_r554226953 for discussion.

In our case, we haven't yet implemented the last breaking change that introduced the new config, so this would be a good time to get this in.

If you are open to this, let me know.  If not, feel free to also let me know and close the issue.

Thank you!

**Comment by victorrodrigues** [comment]
Hey @robrap,  I don't mind matching all the names in the New Relic snippet. Could you provide the PR for this change?

**Comment by robrap** [comment]
Thanks. I may need a week to get to this, but I appreciate the pre-approval.

**Comment by robrap** [comment]
@victorrodrigues: Thanks for merging. I am going to close this Issue.
